services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: porozhnyak
      POSTGRES_PASSWORD: porozhnyak
      POSTGRES_DB: porozhnyak
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U porozhnyak"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
